### ISSUE TITLE
Add a hint to Fusion++ within the category `Troubleshooting loading using Fusion Log`

### ISSUE THREAD

**Issue by kapsiR** [lowleveldesign/debug-recipes#2]
Would be cool to have [Fusion++](https://github.com/awaescher/Fusion) in the toolbelt for .NET assembly issues. (`assemblies/clr-assemblies.md`) 😉

**Comment by lowleveldesign** [comment]
Thanks, @kapsiR. I added a note - Fusion++ is definitely worth mentioning :slightly_smiling_face:
